# generated by datamodel-codegen:
#   filename:  schema.yml

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import AnyUrl, BaseModel, Field


class Mode(Enum):
    text = 'text'
    image = 'image'
    audio = 'audio'
    video = 'video'


class Dataset(BaseModel):
    name: str = Field(..., description='The name of the dataset')
    url: AnyUrl = Field(..., description='Download url for dataset')
    mode: Mode = Field(..., description='Perceptual mode of media assets')
    installer: Optional[str] = Field(
        None, description='Full path to python function that installs the dataset'
    )
    samples: Optional[int] = Field(
        None, description='Number of samples to install from the dataset'
    )
